services:
  
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    image: database:v1
    container_name: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin_pass1234
      - POSTGRES_DB=abcd_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  flask:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 5010:5010
    # dodanie wolumenu
    volumes:
      - ./api:/app
    image: api:v1
    container_name: api
    depends_on:
      - database
    environment:
      - DB_HOST=database
    networks:
      - backend

  broker:
    build:
      context: ./broker
      dockerfile: Dockerfile
    ports: 
      - 8883:8883
    image: broker:v1
    container_name: broker
    networks:
      - backend

  ingestor:
    build:
      context: ./ingestor
      dockerfile: Dockerfile
    image: ingestor:v1
    container_name: ingestor
    depends_on:
      - database
      - broker
    environment:
      - DB_HOST=database
      - MQTT_HOST=broker
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge